name: Testes automatizados

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  executar-testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v5

      - name: Configurar o Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Instalar as dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar os testes com PyTest
        run: pytest -v
